const DumyProduct = [
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"},
    {img: "/image/main/main1.png", link:"#", text : "메인페이지"},
    {img: "/image/main/main2.png", link:"#", text : "쿠폰이벤트"},
    {img: "/image/main/main2.png", link:"#", text: "훈련이벤트"}
]

export default DumyProduct;